---
title: "Our Collaboration Journey"
editor: visual
---

The falcon project is a product of industry collaborations to encourage the development of shared code, expertise, knowledge and products.

Current collaborators are from Roche, Sanofi, Boehringer-Ingelheim, and Moderna. Developers are connected via GitHub for the creation of shared solutions using publicly available analysis packages for R. Developers are invited to browse the falcon project repository and related packages for insights into our template designs.

In the near future, the goal is to develop functionality to create regulatory reporting tables suitable for FDA filing. The long-term objective of this collaboration is to develop an R package that can be used industry wide - developing a cross-industry standard and reducing manual work from a reporting perspective.

We invite further collaboration with additional companies joining this initiative and contributing to the falcon project. Please feel free to contact any of the repository maintainers for additional information and check out the *Developer Journey* page on this website.
