---
name: ✨ Feature Request
description: Request or propose a new feature
title: "[Feature Request]: <title>"
labels: ["enhancement"]
projects: ["cardinal"]
body:
  - type: textarea
    attributes:
      label: Feature description
    validations:
      required: true
