---
name: 🔨 New TLG Template
description: Add a new TLG template
title: "[New TLG]: <title>"
labels: ["new template"]
projects: ["cardinal"]
body:
  - type: textarea
    attributes:
      label: TLG Title/Description
      description: Title and/or a description of the TLG.
      placeholder: TLG title/description
