---
title: About the Project
---

The Cardinal project (previously "falcon") is a product of industry collaboration to encourage the development of shared code, expertise, knowledge, and products.

The goal of this collaboration is to develop an extensive catalog of harmonized ARD-based table, listing, and graph (TLG) templates that can be used industry wide - developing a cross-industry standard and reducing manual work from a reporting perspective.

## Our Collaboration Journey

Current collaborators are from Roche, Sanofi, Boehringer Ingelheim, and Moderna. Developers are connected via [Slack](https://app.slack.com/client/T028PB489D3/C04MQS12MND) and [GitHub](https://github.com/pharmaverse/cardinal) for the creation of shared solutions using publicly available analysis packages for R. Developers are invited to browse the Cardinal project repository and related packages for insight into our template designs.

### Joining as a Collaborator

As always we invite further collaboration and welcome additional companies to join the Cardinal initiative and contribute to the project. Please feel free to contact any of the repository maintainers for more information and check out the section below for more information on joining the project as a developer.

#### Information for Developers

As a pharmaverse collaboration, we invite any interested developers to join the Cardinal team and contribute to template development. To onboard as a developer, please reach out to one of the Cardinal Product Owners ([Vincent Shen](https://github.com/telepath37), [Freeman Wang](https://github.com/freestatman), Kavitha Allala, Lian Lin) to receive access to the Cardinal GitHub repository.

Tasks are assigned and prioritized via issues on our GitHub project board and worked on in development branches. Members of the team will review each other's code and make suggestions before new templates are incorporated into the project catalog.

For information on the process by which developers can add new templates to the catalog, see the [Getting Started page](getting_started.qmd).

We encourage onboarding developers to familiarize themselves with the following packages as they contain functions leveraged by the Cardinal team for TLG creation:

-   [{gtsummary}](https://www.danieldsjoberg.com/gtsummary/): Table creation
-   [{cards}](https://insightsengineering.github.io/cards/): ARD creation
-   [{cardx}](https://insightsengineering.github.io/cardx/): Extended ARD creation functions
-   [{crane}](https://insightsengineering.github.io/crane/): Pharmaceutical-specific table creation functions
-   [{pharmaverseadam}](https://pharmaverse.github.io/pharmaverseadam/): Example synthetic ADaM datasets
