---
title: Template Library Index
date: '`r Sys.Date()`'
---

------------------------------------------------------------------------

### **FDA Tables**
-   [FDA Table 2 -- Baseline Demographic and Clinical Characteristics, Safety Population, Pooled Analyses](table-templates/template-table_02.qmd)

-   [FDA Table 5 -- Duration of Treatment Exposure, Safety Population, Pooled Analyses](table-templates/template-table_05.qmd)

-   [FDA Table 6 -- Overview of Adverse Events, Safety Population, Pooled Analyses](table-templates/template-table_06.qmd)

-   [FDA Table 7 -- Deaths, Safety Population, Pooled Analyses](table-templates/template-table_07.qmd)

-   [FDA Table 8 -- All Individual Patient Deaths, Safety Population, Pooled Analyses](table-templates/template-table_08.qmd)

-   [FDA Table 9 -- Patients With Serious Adverse Events by System Organ Class and Preferred Term, Safety Population, Pooled Analyses](table-templates/template-table_09.qmd)

-   [FDA Table 10 -- Patients With Serious Adverse Events by System Organ Class and FDA Medical Query (Narrow), Safety Population, Pooled Analyses](table-templates/template-table_10.qmd)

-   [FDA Table 11 -- Patients with FDA Medical Query (Narrow) Leading to Treatment Discontinuation, Safety Population, Pooled Analyses](table-templates/template-table_11.qmd)

-   [FDA Table 12 -- Patients With Adverse Events Leading to Treatment Discontinuation by System Organ Class and Preferred Term, Safety Population, Pooled Analyses](table-templates/template-table_12.qmd)

-   [FDA Table 13 -- Patients With Common Adverse Events Occurring at >=X% Frequency, Safety Population, Pooled Analyses](table-templates/template-table_13.qmd)

-   [FDA Table 14 -- Patients With Adverse Events by System Organ Class and FDA Medical Query, Safety Population, Pooled Analyses](table-templates/template-table_14.qmd)

-   [FDA Table 20 -- Adverse Events of Special Interest Assessment, Safety Population, Pooled Analysis (or Trial X)](table-templates/template-table_20.qmd)

-   [FDA Table 21 -- Overview of Serious Adverse Events1 by Demographic Subgroup, Safety Population, Pooled Analysis (or Trial X)](table-templates/template-table_21.qmd)

-   [FDA Table 32 -- Percentage of Patients With Maximum Diastolic Blood Pressure by Category of Blood Pressure Postbaseline, Safety Population, Pooled Analysis](table-templates/template-table_32.qmd)

-   [FDA Table 33 -- Percentage of Patients Meeting Specific Hypotension Levels Postbaseline, Safety Population, Pooled Analysis](table-templates/template-table_33.qmd)

-   [FDA Table 34 -- Patients With Serious Adverse Events by System Organ Class, FDA Medical Query (Narrow), and Preferred Term, Safety Population, Pooled Analysis (or Trial X)](table-templates/template-table_34.qmd)

