---
title: Resources
---

#### FDA Standard Safety Tables and Figures Integrated Guide (v2.0)

Click [here](assets/resources/2025_FDA-STF-IG.pdf) to download.

---

#### Past Talks & Presentations

##### R/Pharma 2025 Online Workshop

- Date: November 3, 2025
- Click [here](assets/resources/RinPharma_2025/cardinal_RinPharma_Workshop_2025.pdf) to download the workshop slide deck.
- Click [here](assets/resources/RinPharma_2025/workshop_QandA.R) to download the workshop Q&A R script.
- Workshop exercises: \ \ \ [\[environment setup\]](assets/resources/RinPharma_2025/demo_setup.R)
  - Demographics Table -- FDA Table 2 \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ [\[exercise\]](assets/resources/RinPharma_2025/demo_01_exercise.R) \ \ \ \ \ [\[solution\]](assets/resources/RinPharma_2025/demo_01_solution.R)
  - Adverse Events Table -- FDA Table 14 \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ [\[exercise\]](assets/resources/RinPharma_2025/demo_02_exercise.R) \ \ \ \  [\[solution\]](assets/resources/RinPharma_2025/demo_02_solution.R)
  - Lab Test Results Table -- Roche Table LBT01 \ \ \ \ \ [\[exercise\]](assets/resources/RinPharma_2025/demo_03_exercise.R) \ \ \ \  [\[solution\]](assets/resources/RinPharma_2025/demo_03_solution.R)

##### PHUSE EU Connect Presentation

- Date: November 6, 2023
- Click [here](assets/resources/cardinal_PHUSE_EU_2023.pptx) to download the presentation slide deck.

##### R/Pharma 2023 Online Workshop

- Date: October 20, 2023
- Click [here](assets/resources/cardinal_RinPharma_Workshop_2023.pptx) to download the workshop slide deck.
