name: Check URLs in docs 📚

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  links:
    name: Links
    uses: phuse-org/devops-toolkit/.github/workflows/urlchecker.yml@main
